export default {
    "0": {
        "id": 0,
        "name": "Cozy Studio in Downtown",
        "thumbnail_image": "/assets/img/bild1.jpg",
        "description": "A charming studio in the heart of the city, perfect for solo travelers or couples.",
        "stars": 4,
        "location": "Downtown, Cityville",
        "price_per_night": "$75",
        "max_guests": 2,
        "category": "Studio",
        "pet_friendly": true,
        "featured": true,
        "host": "WP-BNB FakeGmbH"
    },
    "1": {
        "id": 1,
        "name": "Luxury Penthouse with City View",
        "thumbnail_image": "/assets/img/bild2.jpg",
        "description": "An upscale penthouse with breathtaking city views and modern amenities.",
        "stars": 4,
        "location": "City Center, Cityville",
        "price_per_night": "$250",
        "max_guests": 4,
        "category": "Penthouse",
        "pet_friendly": false,
        "featured": false,
        "host": "WP-BNB FakeGmbH"
    },
    "2": {
        "id": 2,
        "name": "Seaside Retreat",
        "thumbnail_image": "/assets/img/bild1.jpg",
        "description": "A relaxing beachfront apartment with direct ocean access and a private balcony.",
        "stars": 4,
        "location": "Seaview, Beachville",
        "price_per_night": "$120",
        "max_guests": 3,
        "category": "Beachfront",
        "pet_friendly": true,
        "featured": false,
        "host": "WP-BNB FakeGmbH"
    },
    "3": {
        "id": 3,
        "name": "Rustic Mountain Cabin",
        "thumbnail_image": "/assets/img/bild3.jpg",
        "description": "A cozy wooden cabin nestled in the mountains, ideal for nature lovers.",
        "stars": 4,
        "location": "Highlands, Mountville",
        "price_per_night": "$90",
        "max_guests": 5,
        "category": "Cabin",
        "pet_friendly": true,
        "featured": true,
        "host": "WP-BNB FakeGmbH"
    },
    "4": {
        "id": 4,
        "name": "Modern Loft with Skylight",
        "thumbnail_image": "/assets/img/bild3.jpg",
        "description": "A stylish loft with an open floor plan, high ceilings, and a skylight for natural light.",
        "stars": 4,
        "location": "Arts District, Cityville",
        "price_per_night": "$110",
        "max_guests": 2,
        "category": "Loft",
        "pet_friendly": false,
        "featured": false,
        "host": "WP-BNB FakeGmbH"
    },
    "5": {
        "id": 5,
        "name": "Family-Friendly Suburban Home",
        "thumbnail_image": "/assets/img/bild2.jpg",
        "description": "A spacious home in a quiet neighborhood, perfect for families or groups.",
        "stars": 4,
        "location": "Suburbia, Townsville",
        "price_per_night": "$140",
        "max_guests": 6,
        "category": "House",
        "pet_friendly": true,
        "featured": true,
        "host": "WP-BNB FakeGmbH"
    },
    "6": {
        "id": 6,
        "name": "Tiny Home Escape",
        "thumbnail_image": "/assets/img/bild2.jpg",
        "description": "A unique tiny home experience with smart space utilization and a cozy atmosphere.",
        "stars": 5,
        "location": "Green Valley, Countryside",
        "price_per_night": "$65",
        "max_guests": 2,
        "category": "Tiny Home",
        "pet_friendly": false,
        "featured": true,
        "host": "WP-BNB FakeGmbH"
    },
    "7": {
        "id": 7,
        "name": "Chic Urban Apartment",
        "thumbnail_image": "/assets/img/bild1.jpg",
        "description": "A modern apartment in a vibrant urban area, close to shops and restaurants.",
        "stars": 3,
        "location": "Midtown, Cityville",
        "price_per_night": "$100",
        "max_guests": 4,
        "category": "Apartment",
        "pet_friendly": true,
        "featured": false,
        "host": "WP-BNB FakeGmbH"
    },
    "8": {
        "id": 8,
        "name": "Countryside Farmhouse",
        "thumbnail_image": "/assets/img/bild1.jpg",
        "description": "A peaceful farmhouse surrounded by greenery and rolling hills.",
        "stars": 0,
        "location": "Farmville, Rural County",
        "price_per_night": "$85",
        "max_guests": 5,
        "category": "Farmhouse",
        "pet_friendly": true,
        "featured": false,
        "host": "WP-BNB FakeGmbH"
    },
    "9": {
        "id": 9,
        "name": "Historic Townhouse with Garden",
        "thumbnail_image": "/assets/img/bild3.jpg",
        "description": "A beautifully restored historic townhouse with a private garden and vintage decor.",
        "stars": 5,
        "location": "Old Town, Cityville",
        "price_per_night": "$130",
        "max_guests": 3,
        "category": "Townhouse",
        "pet_friendly": false,
        "featured": false,
        "host": "WP-BNB FakeGmbH"
    }
};

